services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: notes_backend
        restart: always
        depends_on:
            - mariadb
        env_file: .env
        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"
        volumes:
            - ./backend:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - PORT=${BACKEND_PORT}
            - DB_NAME=${DB_NAME}
        command: ["npm", "run", "dev"]

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: notes_frontend
        restart: always
        depends_on:
            - backend
        env_file: .env
        ports:
            - "${FRONTEND_PORT}:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: ["npm", "run", "dev"]

    mariadb:
        image: mariadb:latest
        container_name: notes_mariadb
        restart: always
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: rootp

volumes:
    db_data:
